Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Lint/ScriptPermission:
  Exclude:
    - bin/console

Metrics/AbcSize:
  Max: 20